#!/usr/bin/env node

var path = require('path');
var dir = path.resolve(path.dirname(__dirname + "../"));
process.chdir(dir);

var Assets = require('gd-assets');

var config    = Assets.Config.load(dir+'/assets.json');
var pkg       = require(dir+'/package.json');
var outputDir = dir+'/assets';

Assets.Compile(config, pkg, outputDir);
